# Generated by Django 4.1.2 on 2022-10-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Client', models.CharField(max_length=100)),
                ('Numéro', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Code_postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prénom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Ajouté', models.DateTimeField(auto_now_add=True)),
                ('Nom_Client', models.CharField(max_length=100)),
                ('Numéro', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Address', models.CharField(max_length=100)),
                ('Code_postal', models.IntegerField()),
                ('Commentaire', models.CharField(blank=True, max_length=500, null=True)),
                ('Prix', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, choices=[('Fait', 'Fait'), ('en attendant', 'en attendant'), ('annulée', 'annulée')], default='en attendant', max_length=500, null=True)),
                ('Par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.userprofile')),
            ],
        ),
    ]
