# Generated by Django 3.2.14 on 2022-10-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='valeur',
            field=models.IntegerField(default=1),
        ),
    ]
