# Generated by Django 3.2.14 on 2022-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_intervention_valeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Addresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Téléphone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Prénom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
