# Generated by Django 3.2.14 on 2023-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20221027_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Ajouté', models.DateTimeField(auto_now_add=True)),
                ('Nom_Client', models.CharField(max_length=100)),
                ('Numéro', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Code_postal', models.IntegerField()),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
