# Generated by Django 3.2.14 on 2023-10-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='intervention',
        ),
    ]
