# Generated by Django 3.2.14 on 2023-10-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_remove_reclamation_intervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
