# Generated by Django 3.2.14 on 2023-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0011_intervention_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicien',
            name='Addresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='technicien',
            name='Ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
